packages:
  - "apps/*"

saveExact: true
engineStrict: true
allowBuilds:
  '@ast-grep/cli': true
  cpu-features: set this to true or false
  esbuild: true
  protobufjs: set this to true or false
  sharp: true
  ssh2: set this to true or false
