/* Sample skill data for the Skillbase core-app UI kit.
   Mirrors the seed migration (5 example skills) plus a few more for browsing.
   Plain global — loaded before the React scripts. */
window.SKILLS = [
  {
    name: 'commit-helper',
    author: 'anthropic',
    version: '0.4.2',
    icon: 'git-commit-horizontal',
    desc: 'Generates Conventional Commit messages from your staged diff and enforces the allowed type list.',
    long: 'Reads your staged git diff, infers the change type, and writes a Conventional Commit message. Refuses types outside the allowed set (feat, fix, docs, style, refactor, perf, test, build, ci, chore, content, revert).',
    tags: ['git', 'automation', 'claude-code'],
    license: 'MIT',
    invocations: 1284,
    updated: '3d ago',
    agents: ['Claude Code', 'OpenCode'],
    verified: true,
  },
  {
    name: 'test-runner',
    author: 'community',
    version: '1.1.0',
    icon: 'flask-conical',
    desc: 'Runs Vitest across the monorepo and summarizes failures in plain language.',
    long: 'Executes the Vitest suite across every workspace package, then translates failing assertions into a short, plain-language summary with file links and suggested fixes.',
    tags: ['testing', 'vitest', 'opencode'],
    license: 'Apache-2.0',
    invocations: 902,
    updated: '1w ago',
    agents: ['OpenCode'],
    verified: true,
  },
  {
    name: 'spec-writer',
    author: 'skillbase',
    version: '0.2.0',
    icon: 'file-search',
    desc: 'Scaffolds a feature spec from a one-line description following the spec template.',
    long: "Takes a one-line feature description and produces a structured spec file (user scenarios, requirements, success criteria) following the project's spec-template.md.",
    tags: ['specs', 'docs', 'claude-code'],
    license: 'MIT',
    invocations: 671,
    updated: '2w ago',
    agents: ['Claude Code'],
    verified: true,
  },
  {
    name: 'pr-describer',
    author: 'community',
    version: '0.3.1',
    icon: 'git-pull-request',
    desc: 'Writes a pull-request description from the branch diff and linked issues.',
    long: 'Summarizes the full branch diff, groups changes by area, and drafts a PR description with a checklist and links to referenced issues.',
    tags: ['git', 'github', 'automation'],
    license: 'MIT',
    invocations: 540,
    updated: '5d ago',
    agents: ['Claude Code', 'OpenCode'],
    verified: false,
  },
  {
    name: 'migration-author',
    author: 'skillbase',
    version: '0.1.4',
    icon: 'database',
    desc: 'Creates db-migrate SQL up/down pairs with the correct timestamp naming.',
    long: 'Generates a matching pair of YYYYMMDDHHMMSS-name-up.sql / -down.sql files for db-migrate, scaffolds the schema change, and wires the migration into database.json.',
    tags: ['database', 'postgres', 'sql'],
    license: 'Apache-2.0',
    invocations: 318,
    updated: '3w ago',
    agents: ['OpenCode'],
    verified: true,
  },
  {
    name: 'type-doctor',
    author: 'community',
    version: '0.6.0',
    icon: 'stethoscope',
    desc: 'Runs tsc --noEmit, then explains and fixes the top type errors.',
    long: 'Type-checks every package, ranks errors by blast radius, and proposes minimal edits to resolve them while keeping strict mode intact.',
    tags: ['typescript', 'types', 'claude-code'],
    license: 'MIT',
    invocations: 1130,
    updated: '4d ago',
    agents: ['Claude Code', 'OpenCode'],
    verified: true,
  },
];

window.ALL_TAGS = [
  'git',
  'automation',
  'testing',
  'specs',
  'docs',
  'github',
  'database',
  'postgres',
  'sql',
  'typescript',
  'types',
  'vitest',
];
window.ALL_AGENTS = ['Claude Code', 'OpenCode'];
window.ALL_LICENSES = ['MIT', 'Apache-2.0'];
