/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: 'var(--bg)',
        'bg-sunk': 'var(--bg-sunk)',
        surface: 'var(--surface)',
        'surface-2': 'var(--surface-2)',
        fg: 'var(--fg)',
        'fg-muted': 'var(--fg-muted)',
        'fg-faint': 'var(--fg-faint)',
        'fg-onaccent': 'var(--fg-onaccent)',
        'fg-onink': 'var(--fg-onink)',
        border: 'var(--border)',
        'border-strong': 'var(--border-strong)',
        'border-ink': 'var(--border-ink)',
        accent: 'var(--accent)',
        'accent-hover': 'var(--accent-hover)',
        'accent-text': 'var(--accent-text)',
        'accent-wash': 'var(--accent-wash)',
        ring: 'var(--ring)',
        'code-bg': 'var(--code-bg)',
        'code-fg': 'var(--code-fg)',
        'code-border': 'var(--code-border)',
        'code-line': 'var(--code-line)',
        info: 'var(--info)',
        'info-wash': 'var(--info-wash)',
        success: 'var(--success)',
        'success-wash': 'var(--success-wash)',
        warning: 'var(--warning)',
        'warning-wash': 'var(--warning-wash)',
        danger: 'var(--danger)',
        'danger-wash': 'var(--danger-wash)',
      },
      fontFamily: {
        display: 'var(--font-display)',
        sans: 'var(--font-sans)',
        mono: 'var(--font-mono)',
      },
      fontSize: {
        '2xs': 'var(--text-2xs)',
        xs: 'var(--text-xs)',
        sm: 'var(--text-sm)',
        base: 'var(--text-base)',
        md: 'var(--text-md)',
        lg: 'var(--text-lg)',
        xl: 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        '3xl': 'var(--text-3xl)',
        '4xl': 'var(--text-4xl)',
        '5xl': 'var(--text-5xl)',
      },
      spacing: {
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
        10: 'var(--space-10)',
        12: 'var(--space-12)',
        16: 'var(--space-16)',
        20: 'var(--space-20)',
        24: 'var(--space-24)',
        32: 'var(--space-32)',
      },
      borderRadius: {
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
        '2xl': 'var(--radius-2xl)',
        pill: 'var(--radius-pill)',
      },
      boxShadow: {
        xs: 'var(--shadow-xs)',
        sm: 'var(--shadow-sm)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        accent: 'var(--shadow-accent)',
      },
      maxWidth: {
        prose: 'var(--maxw-prose)',
        content: 'var(--maxw-content)',
        wide: 'var(--maxw-wide)',
      },
    },
  },
};
